# Generated by Django 5.2.9 on 2026-01-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fraudapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionresult",
            name="shap_summary",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="time_trends",
            field=models.JSONField(default=list),
        ),
    ]
